### ISSUE TITLE
Document the deployment process

### ISSUE THREAD

**Issue by pmgower** [Little-Rock-Tech-Fest/lrtf-web#9]
Either inside a readme in this repo or somewhere else we need to document a few things:
1. Where is lrtechfest.com deployed
1. How do we deploy changes to lrtechfest.com
1. How are we to access that deployment
1. Where is the database (or looks like mongodb at this point) located?
1. What are the steps to restore or make a backup?

**Comment by curtisweeks** [comment]
These processes have been [documented in Google Drive](https://drive.google.com/file/d/1xtZ2ss9oACf9IRuhWPZU5IPUOGnBZwgk/view?usp=sharing) for anyone that is part of LRTF.

Public information about contributing changes have been [commited to the readme](https://github.com/Little-Rock-Tech-Fest/lrtf-web/commit/d5ca3da6d18514970e21c07d1ac11da11b4c69bd).
